# syntax=docker/dockerfile:1

## Build
FROM golang:1.19.0-buster AS build
RUN mkdir /app
ADD . /app/
WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download


RUN go build -o /cb-service

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /cb-service /cb-service

EXPOSE 1323

#RUN chown -R user:user /app
# don't do this because we need permission to write to sqlite file
#USER nonroot:nonroot

ENTRYPOINT ["/cb-service"]
